// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcR9hRTZBf30QTmxBwfjiK7Kx8LmUzGNA',
    appId: '1:416285618937:web:9c0e0f11cf5ce713a5e828',
    messagingSenderId: '416285618937',
    projectId: 'petcare-8f604',
    authDomain: 'petcare-8f604.firebaseapp.com',
    storageBucket: 'petcare-8f604.firebasestorage.app',
    measurementId: 'G-B0KX5XZ2MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJCOalGVzue8Bn1S9GAuaSOb5FcjERG08',
    appId: '1:416285618937:android:d7566cf040d4bfdea5e828',
    messagingSenderId: '416285618937',
    projectId: 'petcare-8f604',
    storageBucket: 'petcare-8f604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIbonf46plMbY1RPD3v0irm6OT98pEHds',
    appId: '1:416285618937:ios:8ef00adeb8f9e917a5e828',
    messagingSenderId: '416285618937',
    projectId: 'petcare-8f604',
    storageBucket: 'petcare-8f604.firebasestorage.app',
    iosBundleId: 'com.example.petcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIbonf46plMbY1RPD3v0irm6OT98pEHds',
    appId: '1:416285618937:ios:8ef00adeb8f9e917a5e828',
    messagingSenderId: '416285618937',
    projectId: 'petcare-8f604',
    storageBucket: 'petcare-8f604.firebasestorage.app',
    iosBundleId: 'com.example.petcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcR9hRTZBf30QTmxBwfjiK7Kx8LmUzGNA',
    appId: '1:416285618937:web:93acef4c94386462a5e828',
    messagingSenderId: '416285618937',
    projectId: 'petcare-8f604',
    authDomain: 'petcare-8f604.firebaseapp.com',
    storageBucket: 'petcare-8f604.firebasestorage.app',
    measurementId: 'G-TG887288KL',
  );

}